# Используем официальный образ Node.js
FROM node:16-alpine

# Создаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Открываем порт, который использует приложение
EXPOSE 3000

# Команда для запуска приложения
CMD ["npm", "start"]